// <auto-generated />
namespace Shopping.ManageSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class doem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doem));
        
        string IMigrationMetadata.Id
        {
            get { return "202104260732154_doem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
